/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jt2-friend
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        label4 = new java.awt.Label();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setText("3745195876");
        jTextField1.setEnabled(false);

        jScrollPane1.setHorizontalScrollBar(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Verify1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label1.setText("Expected Code");

        label2.setName(""); // NOI18N
        label2.setText("Recieving Code");

        label3.setText("Output");

        jScrollPane2.setHorizontalScrollBar(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane3.setHorizontalScrollBar(null);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane4.setHorizontalScrollBar(null);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        label4.setName(""); // NOI18N
        label4.setText("Fixed Code");

        jScrollPane5.setHorizontalScrollBar(null);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextArea3.setText("");
        jTextArea4.setText("");
        jTextArea5.setText("");
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        week2DigitWork();
    }//GEN-LAST:event_jButton1MouseClicked

    public void week2DigitWork() {
        int[] d_r = new int [10];
        int[] fixedCode = new int[10];
        int[] syndromes = new int [4];
        int[] PQR = new int [3];
        int[] IJAB = new int [4];

        String recieved_digits;
        recieved_digits = jTextField2.getText();
        
        for (int i = 0; i < 10; i++) {
            d_r[i] = 0;
        }
        
        for (int i = 0; i < 10; i++) {
            d_r[i] = Integer.parseInt(String.valueOf(recieved_digits.charAt(i)));
        }
        
        String pqr = "";
        String error = "";
        String ijab = "";
        String fixedCodeStr = "";
        String digits = "";

        syndromes = generateSyndromes4digits(d_r);
        PQR = generatePQR(syndromes);
        
        if (PQR[0] == 0 && PQR[1] == 0 && PQR[2] == 0 ){
            error = "Single";
            IJAB[0] = syndromes[1] / (syndromes[0] == 0 ? 1: syndromes[0]);
            IJAB[2] = syndromes[0];
        } else {
            error = "Double";
            IJAB = generateIJAB(PQR, syndromes);
            if (checkForThreeErrors(PQR, IJAB, d_r) == 1){
                error = "Triple";
            }
        }
        
        if (syndromes[0] == 0 && syndromes[1] == 0 && syndromes[2] == 0 && syndromes[3] == 0 ){
            error = "None";
        } else {
            fixedCode = fixCode(d_r, IJAB);
            for (int i = 0; i < fixedCode.length; i++) {
                if (fixedCode[i] > 9) {
                    error = "Triple";
                }
            }
        }
        
        for (int i = 0; i < 4; i++) {
            digits += syndromes[i];
            digits += ", ";
        }
        
        for (int i = 0; i < 3; i++) {
            pqr += PQR[i];
            pqr += ", ";
        }
        
        for (int i = 0; i < 4; i++) {
            ijab += IJAB[i];
            ijab += ", ";
        }
        
        for (int i = 0; i < 10; i++) {
            fixedCodeStr += fixedCode[i];
        }

        jTextArea1.setText(error);
        jTextArea2.setText(digits);
        jTextArea3.setText(pqr);
        jTextArea4.setText(ijab);
        jTextArea5.setText(fixedCodeStr);
    }

    public int[] generateParity4digits(int[] d){
        d[6] = (4*d[0] + 10*d[1] + 9 * d[2] + 2 * d[3] + d[4] + 7*d[5]) % 11;
        d[7] = (7*d[0] + 8*d[1] + 7*d[2] + d[3] + 9*d[4] + 6*d[5]) % 11;
        d[8] = (9*d[0] + d[1] + 7*d[2] + 8*d[3] + 7*d[4] + 7*d[5]) % 11;
        d[9] = (d[0] + 2*d[1] + 9*d[2] + 10*d[3] + 4*d[4] + d[5]) % 11;

        return d;
    }
    
    public int[] generateSyndromes4digits(int[] d){
        
        int[] s = new int [4];
        
        //s1
        s[0] = (d[0] + d[1] + d[2] + d[3] + d[4] + d[5] + d[6] + d[7] + d[8] + d[9]) 
                % 11;
        //s2
        s[1] = (d[0] + (2 * d[1]) + (3* d[2]) + (4 * d[3]) + (5 * d[4]) +
                (6* d[5]) + (7 * d[6]) + (8*d[7]) + (9*d[8]) + (10 * d[9])) % 11;
        //s3
        s[2] = (d[0] + (4 * d[1]) + (9*d[2])+ (5*d[3]) + (3 * d[4]) + (3* d[5]) +
                (5*d[6]) + (9 * d[7]) + (4 * d[8]) + d[9]) % 11;
        //s4
        s[3] = (d[0] + (8*d[1]) + (5*d[2]) + (9*d[3]) + (4* d[4]) + (7*d[5]) + 
                (2*d[6]) + (6 * d[7]) + (3 * d[8]) + (10*d[9])) % 11;

        return s;
    }
    
    public int[] generatePQR(int[] s){
        
        int[] PQRarr = new int [3];
        int p = mod11fix((s[1] * s[1]) - (s[0] * s[2]));
        int q = mod11fix((s[0] * s[3]) - (s[1] * s[2]));
        int r = mod11fix((s[2] * s[2]) - (s[1] * s[3]));
        
        PQRarr[0] = p;
        PQRarr[1] = q;
        PQRarr[2] = r;
       
        return PQRarr;
    }
    
    public int mod11fix(int val) {
        while (val < 0) {
            val = val + 11;
        }
        val = val % 11;

        return val;
    }
    
    public int modDivision(int val) {
        int testVal = 0;
        for (int i = 0; i< 11; i++) {
            testVal = val * i;
            
            if (testVal % 11 == 1) {
                return i;
            }
        }

        return 0;
    }
    
    public int[] fixCode(int [] originalCode, int [] IJAB) {
        int pos_1 = IJAB[0];
        int pos_2 = IJAB[1];
        int mag_1 = IJAB[2];
        int mag_2 = IJAB[3];
        
//        printArray(IJAB);
        
//        System.out.println("i:");
//        System.out.println(originalCode[pos_1 - 1]);
//        System.out.println("a:");
//        System.out.println(mag_1);
        
        if (pos_1 > 0) {
            originalCode[pos_1 - 1] = mod11fix(originalCode[pos_1 - 1] - mag_1);
        }

        if (pos_2 > 0) {
            originalCode[pos_2 - 1] = mod11fix(originalCode[pos_2 - 1] - mag_2);
        }
        
        return originalCode;
    }
    
    public int[] generateIJAB(int[] PQR, int[] s){
        
        int[] IJAB = new int [4];
        int p = PQR[0];
        int q = PQR[1];
        int r = PQR[2];
 
        int firstPiece = q;
        int secondPiece = squareroot(mod11fix((q*q) - (4 * p * r)));
        int lastPiece = mod11fix(2 * p);
        int i = mod11fix( -firstPiece + secondPiece) * modDivision(lastPiece);
        int j = mod11fix( -firstPiece - secondPiece) * modDivision(lastPiece);
        
        int b = ((mod11fix(i * s[0])) - s[1]) * modDivision(mod11fix(i - j));
        int a = s[0] - b;

        IJAB[0] = mod11fix(i);
        IJAB[1] = mod11fix(j);
        IJAB[2] = mod11fix(a);
        IJAB[3] = mod11fix(b);
       
        return IJAB;
    }
    
    public void printArray(int[] arr) {
        for (int i = 0; i < (arr.length); i++) {
            System.out.println(arr[i]);
        }
    }
    
    public int checkForThreeErrors(int[] PQR, int[] IJAB, int[] d_r) {
        int p = PQR[0];
        int q = PQR[1];
        int r = PQR[2];
        
        if (squareroot(mod11fix((q*q) - (4 * p * r))) == -1) {
            return 1;
        }

        if (IJAB[0] == 0 || IJAB[1] == 0){
            return 1;
        }
        
//        if ((fixCode(d_r, IJAB)).length > d_r.length){
//            return 1;
//        } 
        
        return 0;
    }
    
    
    public int squareroot(int val){
        int testVal = 0;
        
        for (int i = 0; i< 20; i++) {
            testVal = i*i;
            if (testVal % 11 == val) {
                return i;
            }
        }

        return -1;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
